In [1]:
import numpy as np

In [17]:
def mat_transvection(n,i,j,a):
    
    I = np.identity(n)
    x = np.zeros(n*n)
    #print(x)
    e = np.reshape(x,(n,n))
    #print(e)
    e[i-1][j-1] = 1
    #print(e)
    return I+a*e

def mat_permutation(n,i,j):
    I = np.identity(n)
    a = np.copy(I)
    print(a)
    a[i-1][:]=I[j-1][:]
    print(a)
    print(I[i-1][:])
    a[j-1][:]=I[i-1][:]
    print(a)
    return a
    

In [3]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
x = np.zeros(16)

In [5]:
t=np.reshape(x,(4,4))

In [6]:
t

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
type(x)

numpy.ndarray

In [8]:
x = np.zeros(4*4)
e = np.reshape(x,(4,4))
e[1][2] = 1

In [9]:
e

array([[0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
t=mat_transvection(3,1,3,1)

In [11]:
t

array([[1., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
A = [[4,5,14],[1,11,23],[0,2,-5]]

In [13]:
a=np.array(A)
a

array([[ 4,  5, 14],
       [ 1, 11, 23],
       [ 0,  2, -5]])

In [14]:
a[0:][0]
c = []
c.append(a[0:][0])
c
a[2][0]

0

In [15]:
a=np.delete(a, (0), axis=0)
a=np.delete(a, (0), axis=1)
a

array([[11, 23],
       [ 2, -5]])

In [18]:
mat_permutation(3,1,3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 0. 0.]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [19]:
I = np.identity(4)

In [20]:
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
I[0][:]=I[2][:]

In [22]:
I[0][:]

array([0., 0., 1., 0.])