In [2]:
import numpy
import numpy as np

In [3]:
a = [1,3,5,7,9]
b = [3,5,6,7,9]
c = a+ b
print(c)

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]


In [4]:
d = np.array([1,3,5,7,9])
e = np.array([3,5,6,7,9])
f = d + e
print(f)

[ 4  8 11 14 18]


In [5]:
type(f)

numpy.ndarray

In [7]:
f.shape

(5,)

In [11]:
l = [[1,2,3],[4,5,6],[7,8,9]]
a = numpy.array(l)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
a.shape

(3, 3)

In [14]:
print(a.dtype)

int64


In [21]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = complex)
print(M.shape)

(3, 3)


In [22]:
print(M.dtype)

complex128


In [23]:
print(M)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


In [24]:
print(a[0])

[1 2 3]


In [25]:
print(a[1, 2])

6


In [26]:
print(a[1, 1:3])

[5 6]


In [27]:
print(a[:,1])

[2 5 8]


In [30]:
x = np.arange(0,10,1)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
print(numpy.linspace(0,10,25))

[ 0.          0.41666667  0.83333333  1.25        1.66666667  2.08333333
  2.5         2.91666667  3.33333333  3.75        4.16666667  4.58333333
  5.          5.41666667  5.83333333  6.25        6.66666667  7.08333333
  7.5         7.91666667  8.33333333  8.75        9.16666667  9.58333333
 10.        ]


In [32]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [35]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [34]:
print(b.dtype)

float64


In [36]:
d = np.arange(5)
print(d)

[0 1 2 3 4]


In [37]:
d[1] = 9.7

In [38]:
print(d)

[0 9 2 3 4]


In [43]:
d = np.arange(5, dtype=numpy.float)

In [44]:
print(d)

[0. 1. 2. 3. 4.]


In [48]:
N = numpy.random.rand(3,3)
numpy.save('saved-matrix.npy', N)
numpy.load('saved-matrix.npy')

array([[0.79730074, 0.40145704, 0.95290901],
       [0.49856632, 0.61515266, 0.69602994],
       [0.68868371, 0.97685   , 0.90189802]])

In [49]:
a = np.arange(4.0)
b = a * 23.4
c = b/(a+1)
c+= 10
print(c)

[10.   21.7  25.6  27.55]


In [50]:
arr = np.arange(100,200)
select = [5,25,50,75,-5]
print(arr[select])

[105 125 150 175 195]


In [51]:
arr = numpy.arange(10,20)
div_by_3 = arr%3 == 0

In [52]:
print(div_by_3)

[False False  True False False  True False False  True False]


In [53]:
print(arr[div_by_3])

[12 15 18]


In [55]:
print(np.arange(10,20).reshape((2,5)))

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [59]:
N.sort()
print(a)

[0. 1. 2. 3.]


In [58]:
numpy.sort(b)

array([ 0. , 23.4, 46.8, 70.2])

In [61]:
print(M.transpose())

[[1.+0.j 4.+0.j 7.+0.j]
 [2.+0.j 5.+0.j 8.+0.j]
 [3.+0.j 6.+0.j 9.+0.j]]


In [64]:
a = np.array([1,4,3,8,9,2,3], dtype=float)
np.median(a)

3.0